package dev.msfjarvis.tracelog.sample

import dev.msfjarvis.tracelog.annotations.DebugLog

private val messages = arrayListOf<String>()

fun main() {
  debuggableFunction("First parameter")
  println("Captured messages:")
  println(messages.joinToString("\n"))
}

@Suppress("Unused") // Used by the generated bytecode
fun recordMessage(message: Any?) {
  messages += message.toString()
}

@DebugLog
fun debuggableFunction(p0: String): String {
  return "Debugging is cool!"
}
