name: CI

on:
  push:
    branches:
      - main
      - renovate/**

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

    - name: Set up JDK
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
      with:
        distribution: temurin
        java-version: 18

    - name: Cache Kotlin/Native compiler
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      with:
        path: ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'gradle/libs.versions.toml') }}

    - name: Setup Gradle caching
      uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # v2.8.0
      with:
        gradle-home-cache-cleanup: true
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}

    - name: Publish compiler plugin to mavenLocal
      run: ./gradlew :compiler-plugin:publishToMavenLocal

    - name: Run unit tests
      run: ./gradlew check

  publish-release:
    if: "github.event_name == 'push' && github.event.ref == 'refs/heads/main'"
    needs:
      - "check"
    runs-on: macos-13
    permissions:
      actions: read
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

    - name: Set up JDK
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
      with:
        distribution: temurin
        java-version: 18

    - name: Cache Kotlin/Native compiler
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      with:
        path: ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'gradle/libs.versions.toml') }}

    - name: Setup Gradle caching
      uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # v2.8.0
      with:
        gradle-home-cache-cleanup: true
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
        dependency-graph: generate-and-submit

    - name: Publish to Maven Central
      run: ./gradlew -x test -x lint publish :gradle-plugin:publish
      env:
        SONATYPE_USERNAME: msfjarvis
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey : ${{ secrets.NEXUS_PUBLISH_SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword : ${{ secrets.NEXUS_PUBLISH_SIGNING_KEY_PASSWORD }}
